sonar.projectKey=deployguard
sonar.projectName=DeployGuard

sonar.sources=backend/src/main/java,frontend/src

sonar.java.binaries=backend/target/classes

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/coverage/**