apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: deployguard

spec:
  selector:
    app: frontend-deployguard

  ports:
    - protocol: TCP
      port: 5173
      targetPort: 80
      nodePort: 30080

  type: NodePort