name: DevSecOps

on:
  push:
    branches: [main]

jobs:

  code-quality:
    uses: ./.github/workflows/code-quality.yml

  # Secret Scanning
  secret-scanning:
    uses: ./.github/workflows/Secret-scanning.yml

  dependency-checks:
    uses: ./.github/workflows/dependency.yml