# Goal - Ensure the Dockerfiles and Docker images are security tested

name: Docker Scan

on:
  workflow_call:

jobs:
  docker-file-lint-and-scan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        folders:
          - backend
          - frontend

    steps:

      # -----------------------------------
      # Checkout source code
      # -----------------------------------
      - name: Code Checkout
        uses: actions/checkout@v4

      # -----------------------------------
      # Dockerfile Lint
      # -----------------------------------
      - name: ${{ matrix.folders }} Dockerfile Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.folders }}/Dockerfile
          ignore: SC2016

      # -----------------------------------
      # Docker Hub Login
      # -----------------------------------
      - name: Docker Setup [Login]
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -----------------------------------
      # Docker Build
      # -----------------------------------
      - name: Docker Build ${{ matrix.folders }}
        run: docker build -t fahadkh14/deployguard-${{ matrix.folders }}:latest ${{ matrix.folders }}

      # Trivy Vulnerability Scanner
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: fahadkh14/deployguard-${{ matrix.folders }}:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'