# Goal - Ensure no secret have being leaked

name: Secret Scanning 


on:
    workflow_call:

jobs:
    scan-serects:
        runs-on: ubuntu latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0

            - name: Git Leeks
              uses: gitleaks/gitleaks-action@v3
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




